### ISSUE TITLE
Readme sketch Feedback

### ISSUE THREAD

**Issue by CharlieV1lla** [AI-Explanation-Group-Project/xaiunits#87]
Hi all,
Please leave your feedback below. I will appreciate your input for anything you want to mention: Table of contents, writing style, changes, new sections. etc. Please, tell me what do you think of the overview section,  project structure and getting started.

**Comment by Michael-Hollins** [comment]
It's a good start; I've tinkered with the language slightly.

Probably a good idea to have a "Further Resources" section after "Getting Started" which points to the various demos we have as well as points to the documentation (once it's live on gitpages). 

I would also add at least one or two diagrams at the start similar to JR's section in the report which illustrate the kind of insights one can derive. 

It would also be good to add a "Current Features and Future Extensions" section, telling the reader which datasets/types we support, which XAI methods we support (ie everything from Captum), that it's build off PyTorch etc. Here we could also add ideas for further work.
